version: '3.5'

services:

  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.0
    command: mysqld --max-connections=500
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: oltpbench
    ports:
      - "3306:3306"

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metastore
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - ./images/hive-config/hive-schema-2.3.0.postgres.sql:/docker-entrypoint-initdb.d/hive-schema-2.3.0.postgres.sql
      - ./images/hive-config/hive-txn-schema-2.3.0.postgres.sql:/docker-entrypoint-initdb.d/hive-txn-schema-2.3.0.postgres.sql


  metastore:
    image: arctic163/benchmark-hive
    container_name: metastore
    hostname: metastore
    ports:
      - 9083
    volumes:
      - ./images/hive-config/core-site.xml:/etc/hadoop/conf/core-site.xml
      - ./images/hive-config/hive-site.xml:/etc/hive/conf/hive-site.xml
      - ./hive:/tmp/hive/warehouse
    depends_on:
      - postgres

  ams:
    image: arctic163/ams
    container_name: ams
    hostname: ams
    volumes:
      - ./arctic:/tmp/arctic/warehouse
    ports:
      - 1630:1630
      - 1260:1260
    tty: true
    stdin_open: true

  trino:
    image: arctic163/benchmark-trino
    container_name: trino
    hostname: trino
    volumes:
      - ./arctic:/tmp/arctic/warehouse
      - ./hive:/tmp/hive/warehouse
    ports:
      - 9001:8080
    depends_on:
      - ams
      - metastore

  presto:
    image: arctic163/benchmark-presto
    container_name: presto
    hostname: presto
    volumes:
      - ./hive:/tmp/hive/warehouse
    ports:
      - 9002:8080
    depends_on:
      - ams
      - metastore

  spark:
    image: arctic163/benchmark-spark
    container_name: spark
    hostname: spark
    command: ["bash","-c","./sbin/start-thriftserver.sh && tail -f /dev/null"]
    volumes:
      - ./hive:/tmp/hive/warehouse
      - ./arctic:/tmp/arctic/warehouse
      - ./images/hive-config/hive-site.xml:/usr/local/arctic_spark/spark-3.1.3-bin-hadoop2.7/conf/hive-site.xml
    ports:
      - 10000:10000
    depends_on:
      - ams
      - metastore

  lakehouse-benchmark:
    image: arctic163/lakehouse-benchmark
    container_name: lakehouse-benchmark
    hostname: lakehouse-benchmark
    depends_on:
      - trino
    tty: true
    stdin_open: true

  lakehouse-benchmark-ingestion:
    image: arctic163/benchmark-ingestion
    container_name: lakehouse-benchmark-ingestion
    hostname: lakehouse-benchmark-ingestion
    volumes:
      - ./hive:/tmp/hive/warehouse
      - ./arctic:/tmp/arctic/warehouse
    depends_on:
      - mysql
      - ams
      - metastore
    tty: true
    stdin_open: true
    ports:
      - "8081:8081"