# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ maven ]
  pull_request:
    branches: [ maven ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        cache: 'maven'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

  test-cockroachdb:

    needs: build
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: /target/extracted

    services:
      cockroach: # https://hub.docker.com/repository/docker/timveil/cockroachdb-single-node
        image: timveil/cockroachdb-single-node:latest
        env:
          DATABASE_NAME: benchbase
        ports:
          - 26257:26257

    steps:
      - name: Extract TGZ artifact
        working-directory: target
        run: |
          mkdir -p /target/extracted
          tar xvzf *.tgz -C /target/extracted/ --strip-components=1

      - name: AuctionMark
        working-directory: $WORKING_DIRECTORY
        run: |
          java -jar benchbase.jar -b auctionmark -c config/cockroachdb/sample_auctionmark_config.xml --create=true --load=true --execute=true

      - name: CH-benCHmark
        working-directory: $WORKING_DIRECTORY
        run: |
          java -jar benchbase.jar -b tpcc -c config/cockroachdb/sample_tpcc_config.xml --create=true --load=true
          java -jar benchbase.jar -b chbenchmark -c config/cockroachdb/sample_chbenchmark_config.xml --create=true --load=true --execute=true

      - name: Epinions.com
        working-directory: $WORKING_DIRECTORY
        run: |
          java -jar benchbase.jar -b epinions -c config/cockroachdb/sample_epinions_config.xml --create=true --load=true --execute=true

      - name: hyadapt
        working-directory: $WORKING_DIRECTORY
        run: |
          java -jar benchbase.jar -b hyadapt -c config/cockroachdb/sample_hyadapt_config.xml --create=true --load=true --execute=true

      - name: noop
        working-directory: $WORKING_DIRECTORY
        run: |
          java -jar benchbase.jar -b noop -c config/cockroachdb/sample_noop_config.xml --create=true --load=true --execute=true

      - name: Resource Stresser
        working-directory: $WORKING_DIRECTORY
        run: |
          java -jar benchbase.jar -b resourcestresser -c config/cockroachdb/sample_resourcestresser_config.xml --create=true --load=true --execute=true

      - name: SEATS
        working-directory: $WORKING_DIRECTORY
        run: |
          java -jar benchbase.jar -b seats -c config/cockroachdb/sample_seats_config.xml --create=true --load=true --execute=true

      - name: SIBench
        working-directory: $WORKING_DIRECTORY
        run: |
          java -jar benchbase.jar -b sibench -c config/cockroachdb/sample_sibench_config.xml --create=true --load=true --execute=true

      - name: SmallBank
        working-directory: $WORKING_DIRECTORY
        run: |
          java -jar benchbase.jar -b smallbank -c config/cockroachdb/sample_smallbank_config.xml --create=true --load=true --execute=true

      - name: TATP
        working-directory: $WORKING_DIRECTORY
        run: |
          java -jar benchbase.jar -b tatp -c config/cockroachdb/sample_tatp_config.xml --create=true --load=true --execute=true

      - name: TPC-C
        working-directory: $WORKING_DIRECTORY
        run: |
          java -jar benchbase.jar -b tpcc -c config/cockroachdb/sample_tpcc_config.xml --create=true --load=true --execute=true

      - name: TPC-H
        working-directory: $WORKING_DIRECTORY
        run: |
          java -jar benchbase.jar -b tpch -c config/cockroachdb/sample_tpch_config.xml --create=true --load=true --execute=true

      - name: Twitter
        working-directory: $WORKING_DIRECTORY
        run: |
          java -jar benchbase.jar -b twitter -c config/cockroachdb/sample_twitter_config.xml --create=true --load=true --execute=true

      - name: Voter
        working-directory: $WORKING_DIRECTORY
        run: |
          java -jar benchbase.jar -b voter -c config/cockroachdb/sample_voter_config.xml --create=true --load=true --execute=true

      - name: Wikipedia
        working-directory: $WORKING_DIRECTORY
        run: |
          java -jar benchbase.jar -b wikipedia -c config/cockroachdb/sample_wikipedia_config.xml --create=true --load=true --execute=true

      - name: YCSB
        working-directory: $WORKING_DIRECTORY
        run: |
          java -jar benchbase.jar -b ycsb -c config/cockroachdb/sample_ycsb_config.xml --create=true --load=true --execute=true