# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ maven ]
  pull_request:
    branches: [ maven ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        cache: 'maven'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - uses: actions/upload-artifact@v2
      with:
        name: oltpbench2
        path: target/*.tgz
        retention-days: 1

  test-cockroachdb:

    needs: build
    runs-on: ubuntu-latest

    services:
      cockroach: # https://hub.docker.com/repository/docker/timveil/cockroachdb-single-node
        image: timveil/cockroachdb-single-node:latest
        env:
          DATABASE_NAME: oltpbench
        ports:
          - 26257:26257

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: oltpbench2

#      - name: Display structure of downloaded files
#        run: ls -R

      - name: extract artifact
        run: |
          tar xvzf oltpbench2-*.tgz --strip-components=1

      - name: delete artifact
        run: |
          rm -rf oltpbench2-*.tgz

#      - name: Display structure of extracted files
#        run: ls -R

      - name: AuctionMark
        run: |
          java -jar oltpbench2.jar -b auctionmark -c config/cockroachdb/sample_auctionmark_config.xml --create=true --load=true --execute=true

      - name: CH-benCHmark
        run: |
          java -jar oltpbench2.jar -b tpcc -c config/cockroachdb/sample_tpcc_config.xml --create=true --load=true
          java -jar oltpbench2.jar -b chbenchmark -c config/cockroachdb/sample_chbenchmark_config.xml --create=true --load=true --execute=true

      - name: Epinions.com
        run: |
          java -jar oltpbench2.jar -b epinions -c config/cockroachdb/sample_epinions_config.xml --create=true --load=true --execute=true

      - name: hyadapt
        run: |
          java -jar oltpbench2.jar -b hyadapt -c config/cockroachdb/sample_hyadapt_config.xml --create=true --load=true --execute=true

      - name: noop
        run: |
          java -jar oltpbench2.jar -b noop -c config/cockroachdb/sample_noop_config.xml --create=true --load=true --execute=true

      - name: Resource Stresser
        run: |
          java -jar oltpbench2.jar -b resourcestresser -c config/cockroachdb/sample_resourcestresser_config.xml --create=true --load=true --execute=true

      - name: SEATS
        run: |
          java -jar oltpbench2.jar -b seats -c config/cockroachdb/sample_seats_config.xml --create=true --load=true --execute=true

      - name: SIBench
        run: |
          java -jar oltpbench2.jar -b sibench -c config/cockroachdb/sample_sibench_config.xml --create=true --load=true --execute=true

      - name: SmallBank
        run: |
          java -jar oltpbench2.jar -b smallbank -c config/cockroachdb/sample_smallbank_config.xml --create=true --load=true --execute=true

      - name: TATP
        run: |
          java -jar oltpbench2.jar -b tatp -c config/cockroachdb/sample_tatp_config.xml --create=true --load=true --execute=true

      - name: TPC-C
        run: |
          java -jar oltpbench2.jar -b tpcc -c config/cockroachdb/sample_tpcc_config.xml --create=true --load=true --execute=true

      - name: TPC-H
        run: |
          java -jar oltpbench2.jar -b tpch -c config/cockroachdb/sample_tpch_config.xml --create=true --load=true --execute=true

      - name: Twitter
        run: |
          java -jar oltpbench2.jar -b twitter -c config/cockroachdb/sample_twitter_config.xml --create=true --load=true --execute=true

      - name: Voter
        run: |
          java -jar oltpbench2.jar -b voter -c config/cockroachdb/sample_voter_config.xml --create=true --load=true --execute=true

      - name: Wikipedia
        run: |
          java -jar oltpbench2.jar -b wikipedia -c config/cockroachdb/sample_wikipedia_config.xml --create=true --load=true --execute=true

      - name: YCSB
        run: |
          java -jar oltpbench2.jar -b ycsb -c config/cockroachdb/sample_ycsb_config.xml --create=true --load=true --execute=true